services:
  nginx:
    ports:
      - 80:80
  devops-docker-cont:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: yarn start
